version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
  - package-ecosystem: "npm"
    directory: "/packages/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "client"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
