"use client"

import { useEffect, useState } from "react"
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Download } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

const fallback = { stages: [{ key: "accrued", name: "Royalty Accrued", count: 1280, amount: 482500, conversionRate: 100, dropOffRate: 0, averageHoursInStage: 2.4 }, { key: "pooled", name: "Pool Allocation", count: 1094, amount: 438200, conversionRate: 85.5, dropOffRate: 14.5, averageHoursInStage: 7.8 }, { key: "approved", name: "Distribution Review", count: 984, amount: 405900, conversionRate: 89.9, dropOffRate: 10.1, averageHoursInStage: 14.5 }, { key: "distributed", name: "Final Distribution", count: 902, amount: 389600, conversionRate: 91.7, dropOffRate: 8.3, averageHoursInStage: 4.1 }], summary: { totalAccrued: 482500, totalDistributed: 389600, conversionRate: 70.5 } }

export function FunnelChart() {
  const [report, setReport] = useState(fallback)
  useEffect(() => { fetch("/api/analytics/funnel").then((r) => r.ok ? r.json() : fallback).then(setReport).catch(() => setReport(fallback)) }, [])
  const exportCsv = () => { const csv = ["stage,count,amount,conversionRate,dropOffRate", ...report.stages.map((s: any) => `${s.name},${s.count},${s.amount},${s.conversionRate},${s.dropOffRate}`)].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "funnel-analysis.csv"; link.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Royalty Distribution Funnel</h2><p className="text-sm text-muted-foreground">Track accrual, pooling, review, and final distribution conversion.</p></div><Button type="button" variant="outline" onClick={exportCsv} className="gap-2"><Download className="h-4 w-4" />Export CSV</Button></div><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="p-6"><p className="text-sm text-muted-foreground">Accrued Revenue</p><p className="text-2xl font-bold">${report.summary.totalAccrued.toLocaleString()}</p></CardContent></Card><Card><CardContent className="p-6"><p className="text-sm text-muted-foreground">Distributed Revenue</p><p className="text-2xl font-bold">${report.summary.totalDistributed.toLocaleString()}</p></CardContent></Card><Card><CardContent className="p-6"><p className="text-sm text-muted-foreground">Conversion</p><p className="text-2xl font-bold">{report.summary.conversionRate}%</p></CardContent></Card></div><Card><CardHeader><CardTitle>Stage Conversion</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={320}><BarChart data={report.stages}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="count" fill="#3b82f6" name="Transactions" /><Bar dataKey="dropOffRate" fill="#f97316" name="Drop-off %" /></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Stage Health</CardTitle></CardHeader><CardContent className="space-y-4">{report.stages.map((stage: any) => <div key={stage.key} className="space-y-2"><div className="flex items-center justify-between text-sm"><span className="font-medium">{stage.name}</span><span className="text-muted-foreground">{stage.conversionRate}%</span></div><Progress value={stage.conversionRate} /><p className="text-xs text-muted-foreground">{stage.dropOffRate}% drop-off, {stage.averageHoursInStage}h average time in stage</p></div>)}</CardContent></Card></div>
}